/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swing_frame;

import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author ADMIN
 */
public class FormQuyDinh extends javax.swing.JInternalFrame {

    /**
     * Creates new form HotelDetail
     */
    public FormQuyDinh() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setName("Thông tin và Quy định"); // NOI18N
        setVisible(true);

        QD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        QD.setText("<html>\n1. Quý khách vui lòng xuất trình hộ chiếu có thị thực xuất nhập cảnh hợp lệ hoặc CMND (đối với công dân Việt Nam) để nhân viên tiếp tân làm thủ tục thuê phòng.<br>\n2. Khách sạn sẽ không chịu trách nhiệm đối với tiền bạc, vật dụng có giá trị của quý khách bị thất lạc khi không để trong két sắt tại phòng.<br>\n3. Quý khách không được mang vũ khí, chất nổ, chất dễ cháy, ma tuý, hàng quốc cấm, súc vật, các loại hàng hoá và tài sản cồng kềnh vào khách sạn.\n4. Khách sạn chúng tôi có phục vụ ăn uống và giặt là, xin quý khách vui lòng không nấu ăn và giặt giũ trong phòng.<br>\n5. Khi ra khỏi phòng, xin quý khách khoá cửa cẩn thận và tự giữ thẻ chìa khoá.<br>\n6. Xin quý khách không tiếp khách trong phòng ngủ trừ khi được sự đồng ý của lễ tân.<br>\n7. Xin quý khách không được sử dụng phòng ngủ để làm văn phòng liên lạc, cũng không thay đổi vị trí, di chuyển tài sản, đồ đạc của khách sạn từ phòng này sang phòng khác. Nếu quý khách làm vỡ, mất, hỏng tài sản thì phải bồi thường theo thời giá hiện hành.<br>\n8. Xin quý khách không tự ý đổi phòng cho nhau, không nhường phòng cho người khác sử dụng, không đưa thêm người khác vào phòng mình, trường hợp cần thiết quý khách phải báo trước và được sự đồng ý của Lễ tân.<br>\n9. Xin quý khách báo trước cho lễ tân 12 giờ trước khi trả phòng, giờ quy đinh trả phòng là 12 giờ trưa. Đối với quý khách lưu trú dài hạn, xin vui lòng thanh toán chi phí 7 ngày một lần hoặc khi số tiền đến giới hạn phải thanh toán.<br>\n10. Chúng tôi rất trân trọng sự hợp tác của quý khách. Xin liên hệ với Lễ tân nếu quý khách có yêu cầu và thắc mắc.<br>\n</html>");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("<html>\nNỘI QUY KHÁCH SẠN<br>\n(HOTEL REGULATION)<br>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QD, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QD, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QD;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
