/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swing_frame;

import com.mysql.jdbc.Messages;
import com.swing.model.Phong;
import com.swing.repository.Icrud;
import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.InterruptedIOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public String username;
    public String password;

    public Home(String username, String password, String type) {

        initComponents();
        datecourante();
        this.setIconImage(new ImageIcon(getClass().getResource("logohaui.png")).getImage());
        PhanQuyen(type);
        panelTrang.setBackground(Color.white);
        panelDo.setBackground(Color.red);
        panelXanh.setBackground(Color.green);
        labelHello.setText("Hello: " + username);
        this.username = username;
        this.password = password;

    }

    public Home() {
        initComponents();
        datecourante();
        this.setIconImage(new ImageIcon(getClass().getResource("logohaui.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void PhanQuyen(String maQuyen) {
        if (maQuyen.equals("Q02")) {
            jTabbedPane1.remove(1);
            jTabbedPane1.remove(2);
            jTabbedPane1.removeTabAt(1);
//            jTabbedPane1.remove();
            JOptionPane.showMessageDialog(null, "Quyền: Nhân viên.");
        } else if (maQuyen.equals("Q01")) {
            JOptionPane.showMessageDialog(null, "Quyền: Admin.");
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new javax.swing.JDesktopPane();
        panelMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        NguoiDung = new javax.swing.JPanel();
        btnThanhVien = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DanhMuc = new javax.swing.JPanel();
        Home2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnLoaiPhong = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnLoaiPhong1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        QuanLy = new javax.swing.JPanel();
        Home1 = new javax.swing.JButton();
        Home3 = new javax.swing.JButton();
        Home4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ThongTin = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnHoaDon1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JPanel();
        btnThongTinTaiKhoan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnThongTinTaiKhoan1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnThongTinTaiKhoan2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        QuyDinh = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnThongTin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHoiDap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelHello = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelTrang = new javax.swing.JPanel();
        panelXanh = new javax.swing.JPanel();
        panelDo = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        btnThoat2 = new javax.swing.JButton();
        labDate = new javax.swing.JLabel();
        labdate2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 380));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        desk.setBackground(new java.awt.Color(240, 240, 240));

        panelMain.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(0, 953, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        desk.setLayer(panelMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deskLayout.createSequentialGroup()
                    .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(desk);
        desk.setBounds(160, 210, 1200, 450);

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Everest-Photos-HD.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jTabbedPane1.addTab("Trang Chủ", jLabel2);

        btnThanhVien.setBackground(new java.awt.Color(153, 153, 153));
        btnThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/men-icon.png"))); // NOI18N
        btnThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhVienActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel5.setText("Nhân Viên");

        javax.swing.GroupLayout NguoiDungLayout = new javax.swing.GroupLayout(NguoiDung);
        NguoiDung.setLayout(NguoiDungLayout);
        NguoiDungLayout.setHorizontalGroup(
            NguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoiDungLayout.createSequentialGroup()
                .addGroup(NguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NguoiDungLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NguoiDungLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1225, Short.MAX_VALUE))
        );
        NguoiDungLayout.setVerticalGroup(
            NguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoiDungLayout.createSequentialGroup()
                .addComponent(btnThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Người Dùng", NguoiDung);

        Home2.setBackground(new java.awt.Color(153, 153, 153));
        Home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Home-4-icon.png"))); // NOI18N
        Home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel6.setText("Phòng Khách Sạn");

        btnLoaiPhong.setBackground(new java.awt.Color(153, 153, 153));
        btnLoaiPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Household-Mobile-Home-icon.png"))); // NOI18N
        btnLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiPhongActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel15.setText("<html>\n<div align=\"center\"> \nLoại Phòng <br>Khách Sạn\n</div>\n</html>");

        btnLoaiPhong1.setBackground(new java.awt.Color(153, 153, 153));
        btnLoaiPhong1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Beer-Glass-icon.png"))); // NOI18N
        btnLoaiPhong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiPhong1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel16.setText("<html>\n<div align=\"center\"> \nDanh Sách <br>Dịch vụ\n</div>\n</html>");

        javax.swing.GroupLayout DanhMucLayout = new javax.swing.GroupLayout(DanhMuc);
        DanhMuc.setLayout(DanhMucLayout);
        DanhMucLayout.setHorizontalGroup(
            DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DanhMucLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGroup(DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DanhMucLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoaiPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DanhMucLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(929, Short.MAX_VALUE))
        );
        DanhMucLayout.setVerticalGroup(
            DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhMucLayout.createSequentialGroup()
                .addGroup(DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoaiPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh Mục", DanhMuc);

        Home1.setBackground(new java.awt.Color(153, 153, 153));
        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/man-icon.png"))); // NOI18N
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });

        Home3.setBackground(new java.awt.Color(153, 153, 153));
        Home3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Bulleted-List-icon.png"))); // NOI18N
        Home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home3ActionPerformed(evt);
            }
        });

        Home4.setBackground(new java.awt.Color(153, 153, 153));
        Home4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Money-2-2-icon.png"))); // NOI18N
        Home4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel17.setText("<html>\n<div align=\"center\"> \nThống Kê <br>Doanh Thu\n</div>\n</html>");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel18.setText("<html>\n<div align=\"center\"> \nQuản Lý <br>Khách Hàng\n</div>\n</html>");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel19.setText("<html>\n<div align=\"center\"> \nQuản Lý <br> Tài Khoản\n</div>\n</html>");
        jLabel19.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout QuanLyLayout = new javax.swing.GroupLayout(QuanLy);
        QuanLy.setLayout(QuanLyLayout);
        QuanLyLayout.setHorizontalGroup(
            QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyLayout.createSequentialGroup()
                .addGroup(QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuanLyLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Home3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuanLyLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Home4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuanLyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(929, Short.MAX_VALUE))
        );
        QuanLyLayout.setVerticalGroup(
            QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyLayout.createSequentialGroup()
                .addGroup(QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(QuanLyLayout.createSequentialGroup()
                .addComponent(Home3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(QuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản Lý", QuanLy);

        btnHoaDon.setBackground(new java.awt.Color(153, 153, 153));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Finance-Purchase-Order-icon.png"))); // NOI18N
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel11.setText("Danh Sách Đặt Phòng");

        btnHoaDon1.setBackground(new java.awt.Color(153, 153, 153));
        btnHoaDon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Finance-Bill-icon.png"))); // NOI18N
        btnHoaDon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDon1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel20.setText("Hóa Đơn");

        javax.swing.GroupLayout ThongTinLayout = new javax.swing.GroupLayout(ThongTin);
        ThongTin.setLayout(ThongTinLayout);
        ThongTinLayout.setHorizontalGroup(
            ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinLayout.createSequentialGroup()
                .addGroup(ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1077, Short.MAX_VALUE))
        );
        ThongTinLayout.setVerticalGroup(
            ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinLayout.createSequentialGroup()
                .addGroup(ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ThôngTin", ThongTin);

        btnThongTinTaiKhoan.setBackground(new java.awt.Color(153, 153, 153));
        btnThongTinTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/user-man-info-icon_1.png"))); // NOI18N
        btnThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinTaiKhoanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel7.setText("Thông tin tài khoản");

        btnThongTinTaiKhoan1.setBackground(new java.awt.Color(153, 153, 153));
        btnThongTinTaiKhoan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Refresh-icons.png"))); // NOI18N
        btnThongTinTaiKhoan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinTaiKhoan1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel8.setText("Đổi mật khẩu");

        btnThongTinTaiKhoan2.setBackground(new java.awt.Color(153, 153, 153));
        btnThongTinTaiKhoan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/599074-200.png"))); // NOI18N
        btnThongTinTaiKhoan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinTaiKhoan2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel9.setText("Đăng xuất");

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel9))
                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                        .addComponent(btnThongTinTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongTinTaiKhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongTinTaiKhoan2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(929, Short.MAX_VALUE))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaiKhoanLayout.createSequentialGroup()
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongTinTaiKhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTinTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTinTaiKhoan2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tài Khoản", TaiKhoan);

        btnThongTin.setBackground(new java.awt.Color(153, 153, 153));
        btnThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Symbols-Error-icon.png"))); // NOI18N
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel1.setText("Quy Định");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(btnThongTin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHoiDap.setBackground(new java.awt.Color(153, 153, 153));
        btnHoiDap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/faq-icon.png"))); // NOI18N
        btnHoiDap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoiDapActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jLabel3.setText("Hỏi Đáp");

        javax.swing.GroupLayout QuyDinhLayout = new javax.swing.GroupLayout(QuyDinh);
        QuyDinh.setLayout(QuyDinhLayout);
        QuyDinhLayout.setHorizontalGroup(
            QuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuyDinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(QuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuyDinhLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHoiDap, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuyDinhLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)))
                .addContainerGap(1077, Short.MAX_VALUE))
        );
        QuyDinhLayout.setVerticalGroup(
            QuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuyDinhLayout.createSequentialGroup()
                .addComponent(btnHoiDap, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quy Định", QuyDinh);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 10, 1370, 190);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Home");

        labelHello.setFont(new java.awt.Font("Times New Roman", 3, 25)); // NOI18N
        labelHello.setText("Hello");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel12.setText("Phòng bận");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel13.setText("Phòng trống");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel14.setText("Phòng đang dọn");

        javax.swing.GroupLayout panelTrangLayout = new javax.swing.GroupLayout(panelTrang);
        panelTrang.setLayout(panelTrangLayout);
        panelTrangLayout.setHorizontalGroup(
            panelTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTrangLayout.setVerticalGroup(
            panelTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelXanhLayout = new javax.swing.GroupLayout(panelXanh);
        panelXanh.setLayout(panelXanhLayout);
        panelXanhLayout.setHorizontalGroup(
            panelXanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelXanhLayout.setVerticalGroup(
            panelXanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDoLayout = new javax.swing.GroupLayout(panelDo);
        panelDo.setLayout(panelDoLayout);
        panelDoLayout.setHorizontalGroup(
            panelDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelDoLayout.setVerticalGroup(
            panelDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/Apps-Dialog-Shutdown-icon.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThoat1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/94486476_1122733361393125_8303015267500294144_n.png"))); // NOI18N
        btnThoat1.setText("Reload");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        btnThoat2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThoat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/94429942_234771344408389_7412829844536295424_n.png"))); // NOI18N
        btnThoat2.setText("Home");
        btnThoat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat2ActionPerformed(evt);
            }
        });

        labDate.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N

        labdate2.setFont(new java.awt.Font("1979 Dot Matrix", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labdate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelXanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnThoat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(btnThoat2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThoat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))
                            .addComponent(panelDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelXanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 190, 150, 510);

        setSize(new java.awt.Dimension(1382, 786));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListDanhSachDatPhong fr = new ListDanhSachDatPhong();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhVienActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        List_des_Conddats lc = new List_des_Conddats();
        this.desk.add(lc);
        try {
            lc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        lc.show();
    }//GEN-LAST:event_btnThanhVienActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        FormQuyDinh fr = new FormQuyDinh();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void btnHoiDapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoiDapActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        FormHoiDap fr = new FormHoiDap();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnHoiDapActionPerformed

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home1ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListTaiKhoan fr = new ListTaiKhoan();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_Home1ActionPerformed

    private void Home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home2ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListPhongKhachSan fr = new ListPhongKhachSan();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_Home2ActionPerformed
    //thong tin tai khoan
    private void btnThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinTaiKhoanActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        FormThongTinTaiKhoan fr = new FormThongTinTaiKhoan(username);
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnThongTinTaiKhoanActionPerformed
//doi mat khau
    private void btnThongTinTaiKhoan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinTaiKhoan1ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        FormDoiMatKhau fr = new FormDoiMatKhau(username, password);
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnThongTinTaiKhoan1ActionPerformed
//    Dang Xuat
    private void btnThongTinTaiKhoan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinTaiKhoan2ActionPerformed
        this.dispose();
        new LoginGUI().show();
    }//GEN-LAST:event_btnThongTinTaiKhoan2ActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.desk.removeAll();
        this.desk.repaint();
        FormHome fr = new FormHome();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiPhongActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListLoaiPhong fr = new ListLoaiPhong();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnLoaiPhongActionPerformed

    private void btnLoaiPhong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiPhong1ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListDanhSachDoAn fr = new ListDanhSachDoAn();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnLoaiPhong1ActionPerformed

    private void Home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home3ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListKhachHang fr = new ListKhachHang();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_Home3ActionPerformed

    private void Home4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home4ActionPerformed
         this.desk.removeAll();
        this.desk.repaint();
        FormDoanhThu fr = new FormDoanhThu();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_Home4ActionPerformed

    private void btnHoaDon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDon1ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        ListDanhSachDoanhThu fr = new ListDanhSachDoanhThu();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();    }//GEN-LAST:event_btnHoaDon1ActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
       this.desk.removeAll();
        this.desk.repaint();
        FormHome fr = new FormHome();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    private void btnThoat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat2ActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        FormHome fr = new FormHome();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_btnThoat2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.desk.removeAll();
        this.desk.repaint();
        FormHome fr = new FormHome();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_formWindowOpened
    public void loadForm(){
        this.desk.removeAll();
        this.desk.repaint();
        FormHome fr = new FormHome();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.desk.removeAll();
        this.desk.repaint();
        FormHome fr = new FormHome();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public void datecourante() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();

                    int seconds = cal.get(Calendar.SECOND);
                    int minus = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);

                    int AP = cal.get(Calendar.AM_PM);
                    String pa;
                    if (AP == 1) {
                        pa = "PM";
                    } else {
                        pa = "AM";
                    }

                    int date = cal.get(Calendar.DAY_OF_MONTH);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);

                    labDate.setText(hour + ":" + minus + ":" + seconds + " " + pa);
                    labdate2.setText(date + "/" + month + "/" + year);
                    try {
                        sleep(1000);

                    } catch (InterruptedException e) {
                        Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, e);
                    }
                }

            }
        };
        clock.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DanhMuc;
    private javax.swing.JButton Home1;
    private javax.swing.JButton Home2;
    private javax.swing.JButton Home3;
    private javax.swing.JButton Home4;
    private javax.swing.JPanel NguoiDung;
    private javax.swing.JPanel QuanLy;
    private javax.swing.JPanel QuyDinh;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel ThongTin;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnHoaDon1;
    private javax.swing.JButton btnHoiDap;
    private javax.swing.JButton btnLoaiPhong;
    private javax.swing.JButton btnLoaiPhong1;
    private javax.swing.JButton btnThanhVien;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnThoat2;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnThongTinTaiKhoan;
    private javax.swing.JButton btnThongTinTaiKhoan1;
    private javax.swing.JButton btnThongTinTaiKhoan2;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labdate2;
    private javax.swing.JLabel labelHello;
    private javax.swing.JPanel panelDo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTrang;
    private javax.swing.JPanel panelXanh;
    // End of variables declaration//GEN-END:variables
}
